# Generated by Django 2.0.1 on 2018-01-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoideal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
