# Generated by Django 2.0.1 on 2018-01-31 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipoideal', '0002_jugador_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demarcacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_arqueros', models.PositiveIntegerField()),
                ('cantidad_defensas', models.PositiveIntegerField()),
                ('cantidad_centrocampistas', models.PositiveIntegerField()),
                ('cantidad_delanteros', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='posicion',
        ),
        migrations.AddField(
            model_name='jugador',
            name='demarcacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Demarcacion', to='equipoideal.Demarcacion'),
        ),
    ]
