# Generated by Django 2.0.1 on 2018-02-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0001_initial'),
        ('equipoideal', '0003_auto_20180131_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacionEquipoIdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataque', models.FloatField()),
                ('defensa', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polla.Usuario')),
            ],
        ),
    ]
